### Plan
- Learning Pandas with intention of understanding data
- cleaning and Processing before doing any Analysis


## Findings

- The dataset covers `541909` transactions from `01-02-2011` to `31-10-2011`.The primary location `United Kingdom` which concentrated one geographic
- There are `4372` unique customers but `25900` unique invoices this means avg customer placed `6` orders approximately
- the data set contains negative quantity returns we must separate them when doing revenue analysis
- `Customer IDs` have some missing values they might be guest customers without creating id they purchased we must spearate them when doing customer segment analysis
- Top product `White Hanging heart holder` frequency of product does not indicate revenue.cheap Product may have highest frequency but does not contribute much to revenue so we must `calculate revenue per each product`

- this is a python library used to clean and process data

In [ ]:
import pandas as pd

In [6]:
df = pd.read_csv(r"C:\Users\prave\OneDrive\Desktop\ai-engineer-journey\csv_files\Online_Retail.csv",encoding='latin1')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [8]:
rows = df.shape[0]
columns = df.shape[1]
total_data_points = df.shape[0]*df.shape[1]

print(f"Total rows - {rows}")
print(f"Total Columns - {columns}")
print(f"Total data points in data set - {total_data_points}")

Total rows - 541909
Total Columns - 8
Total data points in data set - 4335272

In [10]:
for i,column in enumerate(df.columns):
    print(f"{i+1}. {column}")

1. InvoiceNo
2. StockCode
3. Description
4. Quantity
5. InvoiceDate
6. UnitPrice
7. CustomerID
8. Country

In [11]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [12]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,09-12-2011 12:50,0.85,12680.0,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,09-12-2011 12:50,2.10,12680.0,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,09-12-2011 12:50,4.15,12680.0,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,09-12-2011 12:50,4.15,12680.0,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,09-12-2011 12:50,4.95,12680.0,France

In [13]:
df.sample(5)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
490662,578065,22114,HOT WATER BOTTLE TEA AND SYMPATHY,1,22-11-2011 15:41,8.29,NaN,United Kingdom
29340,538744,22630,DOLLY GIRL LUNCH BOX,1,14-12-2010 11:26,1.95,15356.0,United Kingdom
475790,576915,23166,MEDIUM CERAMIC TOP STORAGE JAR,6,17-11-2011 10:21,1.25,17461.0,United Kingdom
370025,569123,21647,ASSORTED TUTTI FRUTTI LARGE PURSE,2,30-09-2011 13:09,2.10,12748.0,United Kingdom
392902,570733,23048,SET OF 10 LANTERNS FAIRY LIGHT STAR,2,12-10-2011 11:33,4.15,17190.0,United Kingdom

In [14]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

In [16]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [18]:
df['Country'].value_counts().head(10)

Country
United Kingdom    495478
Germany             9495
France              8557
EIRE                8196
Spain               2533
Netherlands         2371
Belgium             2069
Switzerland         2002
Portugal            1519
Australia           1259
Name: count, dtype: int64

In [19]:
df['Description'].value_counts().head(10)

Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
ASSORTED COLOUR BIRD ORNAMENT         1501
SET OF 3 CAKE TINS PANTRY DESIGN      1473
PACK OF 72 RETROSPOT CAKE CASES       1385
LUNCH BAG  BLACK SKULL.               1350
NATURAL SLATE HEART CHALKBOARD        1280
Name: count, dtype: int64

In [20]:
df['CustomerID'].nunique()

4372

In [21]:
df['StockCode'].nunique()

4070

In [23]:
df['InvoiceNo'].nunique()

25900

In [28]:
print(f"Average Unit Price - {df['UnitPrice'].mean():.3f}")

Average Unit Price - 4.611

In [29]:
print(f"min invoice date {df['InvoiceDate'].min()}")

min invoice date 01-02-2011 08:23

In [30]:
print(f"max invoice date {df['InvoiceDate'].max()}")

max invoice date 31-10-2011 17:19

In [31]:
print(25900/4372)

5.924062214089662

In [32]:
df['InvoiceNo'].count()

np.int64(541909)