### Plan
- Prepare in depth of EDA

In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\prave\OneDrive\Desktop\ai-engineer-journey\csv_files\Online_Retail.csv",encoding="latin1")

In [2]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [4]:
print(f"Total Rows {df.shape[0]}")
print(f"Total Columns {df.shape[1]}")
print(f"Total Data Points {df.shape[0] * df.shape[1]}")

Total Rows 541909
Total Columns 8
Total Data Points 4335272

In [5]:
for i,column in enumerate(df.columns):
    print(f"{i+1}. {column}")

1. InvoiceNo
2. StockCode
3. Description
4. Quantity
5. InvoiceDate
6. UnitPrice
7. CustomerID
8. Country

In [7]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [10]:
print(f"Unique Invoices -{df['InvoiceNo'].nunique()} ")
print(f"Unique Customers -{df['CustomerID'].nunique()} ")
print(f"Unique Products -{df['StockCode'].nunique()} ")

Unique Invoices -25900
Unique Customers -4372
Unique Products -4070

In [11]:
print("Top 10 Countries with Most transactions")

df['Country'].value_counts().head(10)

Top 10 Countries with Most transactions

Country
United Kingdom    495478
Germany             9495
France              8557
EIRE                8196
Spain               2533
Netherlands         2371
Belgium             2069
Switzerland         2002
Portugal            1519
Australia           1259
Name: count, dtype: int64

In [13]:
print("Top 10 Products with most transactions" )
df['Description'].value_counts().head(10)

Top 10 Products with most transactions

Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
ASSORTED COLOUR BIRD ORNAMENT         1501
SET OF 3 CAKE TINS PANTRY DESIGN      1473
PACK OF 72 RETROSPOT CAKE CASES       1385
LUNCH BAG  BLACK SKULL.               1350
NATURAL SLATE HEART CHALKBOARD        1280
Name: count, dtype: int64

In [19]:
print(f"Avg Unit Price {df['UnitPrice'].mean():.2f}")

Avg Unit Price 4.61

In [16]:
print(f"Avg Quantity {df['Quantity'].mean():.2f}")

Avg Quantity 9.55

In [20]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

#### Before Cleaning data i always record my initial shape,data types and missing value counts and i compare this with against the baseline

In [23]:
df.shape

(541909, 8)

df.dtypes

In [22]:
df.isnull().sum()

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

### Looking into missing Values

In [30]:
total_rows = len(df)
missing_customers = df['CustomerID'].isnull().sum()
missing_products = df['Description'].isnull().sum()

print(f"Total rows {total_rows}")
print(f"Missing Customers {missing_customers} rows with {missing_customers/total_rows*100:.2f} %")
print(f"Missing Products {missing_products} rows with {missing_products/total_rows*100:.2f} %")

Total rows 541909
Missing Customers 135080 rows with 24.93 %
Missing Products 1454 rows with 0.27 %

#### Looking inot customerIDs
- i will create two separate Dataframes one with only customers for customer analysis and another dataframe with all rows for Revenue analysis
- becuase the given transactions still represent original transactions with actual revenue

In [32]:
df[df['CustomerID'].isnull()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,01-12-2010 11:52,0.00,NaN,United Kingdom
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,01-12-2010 14:32,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,01-12-2010 14:32,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,01-12-2010 14:32,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,01-12-2010 14:32,1.66,NaN,United Kingdom

In [33]:
df_with_customers = df[df['CustomerID'].notna()].copy()
with_all_transactions = df.copy()

print(f"Customers with customerIDs {len(df_with_customers)} rows")
print(f"Customers with all transactions {len(with_all_transactions)} rows")

Customers with customerIDs 406829 rows
Customers with all transactions 541909 rows

#### Looking Negative Quanitites

In [46]:
negative_rows = df[df['Quantity'] < 0]

print(f"Total Negative rows {len(negative_rows)}")
print(f"Percentage of Negative rows {len(negative_rows)/len(df)*100:.1f} %\n")


print("Sample Negative Rows\n")

print(negative_rows[['InvoiceNo','StockCode','Description','Quantity']].head(10))

print("\nDo Negative invoices start with special characters\n")


negative_rows['InvoiceNo'].str[0].value_counts()

Total Negative rows 10624
Percentage of Negative rows 2.0 %

Sample Negative Rows

    InvoiceNo StockCode                        Description  Quantity
141   C536379         D                           Discount        -1
154   C536383    35004C    SET OF 3 COLOURED  FLYING DUCKS        -1
235   C536391     22556     PLASTERS IN TIN CIRCUS PARADE        -12
236   C536391     21984   PACK OF 12 PINK PAISLEY TISSUES        -24
237   C536391     21983   PACK OF 12 BLUE PAISLEY TISSUES        -24
238   C536391     21980  PACK OF 12 RED RETROSPOT TISSUES        -24
239   C536391     21484        CHICK GREY HOT WATER BOTTLE       -12
240   C536391     22557   PLASTERS IN TIN VINTAGE PAISLEY        -12
241   C536391     22553             PLASTERS IN TIN SKULLS       -24
939   C536506     22960           JAM MAKING SET WITH JARS        -6

Do Negative invoices start with special characters

InvoiceNo
C    9288
5    1336
Name: count, dtype: int64

In [54]:
df_sales = df[df['Quantity']>0].copy()
df_returns = df[df['Quantity']<0].copy()

print(f"Total Sales Transactions {len(df_sales)}")
print(f"Total Sales Returns transactions {len(df_returns)}")

df_sales['Revenue'] = df_sales['Quantity'] * df_sales['UnitPrice']

print("\n Total Sales Revenue")
print(f"\n$ {df_sales['Revenue'].sum():,.2f}")

Total Sales Transactions 531285
Total Sales Returns transactions 10624

 Total Sales Revenue

$ 10,644,560.42