In [1]:
import pandas as pd

df = pd.read_csv(r"C:\Users\prave\OneDrive\Desktop\ai-engineer-journey\csv_files\Online_Retail.csv",encoding="latin1")

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

#### Understanding Data - What actually contains

##### 1. Understand how big data it is

In [2]:
rows = df.shape[0]
print(f"Total Rows - {rows}")

columns = df.shape[1]
print(f"\nTotal columns - {columns}")

total_points = df.shape[0] * df.shape[1]
print(f"\nTotal Data Points {total_points}")

Total Rows - 541909

Total columns - 8

Total Data Points 4335272

##### 2. Understaing each Column

1. `InvoiceNo` - Unique invoice id for each transactions
2. `StockCode` - Unique Code for each product
3. `Description` - Proudct name
4. `Quantity` - How many products are sold
5. `InvoiceDate` - date of the sale happend
6. `UnitPrice` - price of product
7. `CustomerID` - Unique customer id for each customer
8. `Country` - which country that customer belongs to

In [3]:
for i,column in enumerate(df.columns):
    print(f"{i+1}. {column}")

1. InvoiceNo
2. StockCode
3. Description
4. Quantity
5. InvoiceDate
6. UnitPrice
7. CustomerID
8. Country

##### 3. Understaning Data types

In [4]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

##### 4. Basic Statistics

In [5]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

#### Understaning Missing Values

In [13]:
print(df.shape)

print(f"\n{df.dtypes}")

print(f"\n{df.isnull().sum()}")

(541909, 8)

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [18]:
total_rows = len(df)

total_desc = df['Description'].isnull().sum()

total_cust = df['CustomerID'].isnull().sum()

print(f"Total Description missing count {total_desc} with {total_desc/total_rows*100:.2f} %")

print(f"Total Customers missing count {total_cust} with {total_cust/total_rows*100:.2f} %")

Total Description missing count 1454 with 0.27 %
Total Customers missing count 135080 with 24.93 %

##### 1. Looking into Customer missing values
- i want to separate customers into two data frames one with without missing values for `customer analysis`
- one with all customers with `revenue analaysis`

In [4]:
df_with_customers = df[df['CustomerID'].notna()].copy()
print(f"total_customers with ids {len(df_with_customers)}")

df_with_all_customers = df.copy()
print(f"total_customers {len(df_with_all_customers)}")

total_customers with ids 406829
total_customers 541909

##### 2. Looking into Negative Qauntities

In [2]:
negative_quantities = df[df['Quantity'] < 0]

print(f"Negative quantities rows {len(negative_quantities)} with {len(negative_quantities)/len(df)*100:.2f} %\n ")


negative_quantities[['InvoiceNo','StockCode','Description','Quantity','InvoiceDate','UnitPrice','CustomerID']].head()


negative_quantities['InvoiceNo'].str[0].head(10)

NameError: name 'df' is not defined

In [21]:
df_sales = df[df['Quantity'] > 0].copy()
df_returns = df[df['Quantity'] < 0].copy()

print(f"Sales transactions {len(df_sales)}")
print(f"Sales return transactions {len(df_returns)}")


df_sales['Revenue'] = df_sales['Quantity'] * df_sales['UnitPrice']
print(f"\nTotal revenue {df_sales['Revenue'].sum():,.2f}$\n")

df_sales.head()

Sales transactions 531285
Sales return transactions 10624

Total revenue 10,644,560.42$

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Revenue
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom,15.30
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom,22.00
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom,20.34
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom,20.34