#### Goal - Without writing single code to answer Business Questions based on data

In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\prave\OneDrive\Desktop\ai-engineer-journey\csv_files\Online_Retail.csv",encoding="latin1")

df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

In [5]:
print(f"row data points {df.shape[0]}")
print(f"column data points {df.shape[1]}")
print(f"total data points {df.shape[0]*df.shape[1]}")

row data points 541909
column data points 8
total data points 4335272

In [8]:
for i,column in enumerate(df.columns):
    print(f"{i+1}. {column}")

1. InvoiceNo
2. StockCode
3. Description
4. Quantity
5. InvoiceDate
6. UnitPrice
7. CustomerID
8. Country

In [10]:
df.dtypes

InvoiceNo       object
StockCode       object
Description     object
Quantity         int64
InvoiceDate     object
UnitPrice      float64
CustomerID     float64
Country         object
dtype: object

In [13]:
df.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [14]:
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,01-12-2010 08:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,01-12-2010 08:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,01-12-2010 08:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,01-12-2010 08:26,3.39,17850.0,United Kingdom

## Business Questions based on columns

#### 1. ID/Key Columns

In [18]:
print(f"Unique Invoice No - {df['InvoiceNo'].nunique()}")

print(f"Unique Stock code - {df['StockCode'].nunique()}")

print(F"Unique Customer IDs - {df['CustomerID'].nunique()}")


# Customer purchasing the no of orders 

print(f"Per customer purchase count  {df['InvoiceNo'].nunique() / df['CustomerID'].nunique()}")

Unique Invoice No - 25900
Unique Stock code - 4070
Unique Customer IDs - 4372
Per customer purchase count  5.924062214089662

#### 2. Category / Grouping Columns

In [23]:
print("Country Segmentation\n")

print(df['Country'].value_counts().head(10))

Country Segmentation

Country
United Kingdom    495478
Germany             9495
France              8557
EIRE                8196
Spain               2533
Netherlands         2371
Belgium             2069
Switzerland         2002
Portugal            1519
Australia           1259
Name: count, dtype: int64

#### 3. Subject Columns

In [24]:
print("Product unique counts\n")

df['Description'].value_counts().head(10)

Product unique counts

Description
WHITE HANGING HEART T-LIGHT HOLDER    2369
REGENCY CAKESTAND 3 TIER              2200
JUMBO BAG RED RETROSPOT               2159
PARTY BUNTING                         1727
LUNCH BAG RED RETROSPOT               1638
ASSORTED COLOUR BIRD ORNAMENT         1501
SET OF 3 CAKE TINS PANTRY DESIGN      1473
PACK OF 72 RETROSPOT CAKE CASES       1385
LUNCH BAG  BLACK SKULL.               1350
NATURAL SLATE HEART CHALKBOARD        1280
Name: count, dtype: int64

#### 4. Numeric Measure columns

In [30]:
print(f"Avg of Unit Price - {df['UnitPrice'].mean():.2f}")
print(f" Total Quantity - {df['Quantity'].sum()}")

Avg of Unit Price - 4.61
 Total Quantity - 5176450

#### 5. Date columns

In [31]:
print(f" This dataset Date range between {df['InvoiceDate'].min()} from {df['InvoiceDate'].max()}")

 This dataset Date range between 01-02-2011 08:23 from 31-10-2011 17:19